### ISSUE TITLE
Fireflies don't glow with Complementary Shader

### ISSUE THREAD

**Issue by theavandiepen** [Anxietie/Ambient-Fireflies#1]
Perhaps there's a setting for Complementary Reimagined that I'm missing, but the fireflies don't glow when the shader is on. The particles they emit work just fine, but their little glowy bits on their butts (which glow so nicely without the shader on) don't emit light

**Comment by Anxietie** [comment]
will look into this when i have time.

**Comment by theavandiepen** [comment]
Thank you!

**Comment by Anxietie** [comment]
can you please provide ur mod list?

**Comment by Anxietie** [comment]
watch this recording: https://imgur.com/a/EYOGCcd (it was too large to attach to this comment)
without shaders the light from the blaze is bright and emits over a larger area. however, when shaders are turned on, the light gets smoothed out and the area that the light emits over is smaller (the light itself also appears dimmer). the same is true for the fireflies; they still emit light, but it is just extremely faint which is intended. since normally without shaders, they dont produce much light. with shaders, though, the light is hard to notice.

mod list used in video:
![image](https://github.com/Anxietie/Ambient-Fireflies/assets/84636109/db0db04a-5d2d-42f9-805d-b5a55061ea65)
